<template>
  <article class="o-page">
    <header class="o-page__heading">
      <div class="o-page__inner">
        <h1 class="mb-0">Spacings Utility Classes</h1>
      </div>
    </header>
    <div class="o-page__wrapper">
      <div class="o-page__content">
        <section class="o-page__section" id="introduction">
          <div class="o-page__inner">
            <p>
              In this section we will find utility classes which can help us
              with: <span class="ff-mono">margins</span>,
              <span class="ff-mono">paddings</span> and how to work with them in
              responsive design scenarios.
            </p>

            <p class="mb-0">
              You can find these classes in
              <span class="c-important"
                >08_utilities/utilities.spacings.scss</span
              >
              file.
            </p>
          </div>
        </section>
        <section class="o-page__section" id="spacings">
          <div class="o-page__inner">
            <header class="o-page__header">
              <h2>Spacings</h2>
            </header>
            <p>
              We're using 2 types of spacings:
              <span class="ff-mono">margin</span>&nbsp;and
              <span class="ff-mono">padding</span>.
              <span class="ff-mono">Margins</span> adds outer space between
              elements, <span class="ff-mono">paddings</span> inner space. If we
              want to add space between two elements, we will use
              <span class="ff-mono">margin</span>&nbsp;(top, right, bottom,
              left). We will use <span class="ff-mono">padding</span>&nbsp;(top,
              right, bottom, left) if we want to add space between borders of
              element and its content.
            </p>

            <p>
              Utility classes for spacings in DS are genrated, in
              <span class="c-important"
                >08_utilities/utilities.spacings.scss</span
              >
              we can find:
              <span class="c-important"
                >@include margin($gaps-stop, $increment);</span
              >&nbsp;<span class="c-important"
                >@include padding($gaps-stop, $increment);</span
              >
            </p>

            <p>
              Those lines are including
              <span class="ff-mono">mixins</span> which are generating utility
              classes for spacings. Each mixin contains two variables:
              <span class="c-important">$gaps-stop</span> &
              <span class="c-important">$increment</span>

              <!-- <span class="c-important">$gaps-stop</span
              >&nbsp;&ndash;&nbsp;serves as maximum value of spacing, value of this variable is by default 64(px)<br />
              <span class="c-important">$increment</span>&nbsp;&ndash;&nbsp; -->
            </p>

            <table class="c-table mb-lg">
              <thead>
                <tr>
                  <th>Variable</th>
                  <th>Rule</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <span class="c-important">$gaps-stop</span>
                  </td>
                  <td>
                    <span class="fsi">64(px)</span>
                  </td>
                  <td>
                    This variable indicated max value of gap that will be
                    genrated, by default this is 64px. Maximum spacing which
                    will DS generate utility class for is 64px, f.e.:
                    <span class="c-important">.mb-64</span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="c-important">$increment</span>
                  </td>
                  <td>
                    <span class="fsi">4(px)</span>
                  </td>
                  <td>
                    By value of this variable will be increased size of the
                    generated spacing, f.e. let's use 4px (default) utility
                    classes for
                    <span class="ff-mono">padding-right</span> generated by DS
                    will be:<br />
                    <span class="c-important">.pr-4</span>,&nbsp;<span
                      class="c-important"
                      >.pr-8</span
                    >...<span class="c-important">.pr-64</span>
                  </td>
                </tr>
              </tbody>
            </table>

            <p>
              In example below we can see pattern of how utility classes are
              made, we used <span class="ff-mono">margin-top</span>, but process
              is same for all directions, <span class="ff-mono">margin</span> or
              <span class="ff-mono">padding</span>.
            </p>
            <code-block
              lang="css"
              :code="GENERATED_SPACING_CLASSES_EXAMPLE"
              class="mb-lg"
              :copy="false"
            />

            <p>
              We can see that DS is providing more, than just directional
              utility classes.
            </p>

            <table class="c-table mb-lg">
              <thead>
                <tr>
                  <th>Class Example</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <div class="o-flex">
                      <span class="c-important">.m-0&nbsp;</span>&nbsp;|&nbsp;
                      <span class="c-important">.m-16</span>
                    </div>
                    <div class="o-flex">
                      <span class="c-important">.p-0&nbsp;</span>&nbsp;|&nbsp;
                      <span class="c-important">.p-16</span>
                    </div>
                  </td>
                  <td>
                    Will set spacing property to
                    <span class="fwb">all directions</span>.
                  </td>
                </tr>
                <tr>
                  <td>
                    <div class="o-flex">
                      <span class="c-important">.mt-0</span>&nbsp;|&nbsp;
                      <span class="c-important">.mr-32</span>
                    </div>
                    <div class="o-flex">
                      <span class="c-important">.pb-8</span>&nbsp;|&nbsp;
                      <span class="c-important">.pl-48</span>
                    </div>
                  </td>
                  <td>
                    Will set spacing property for
                    <span class="fwb">just one direction</span> (top, right,
                    bottom, left).
                    <span class="fsi"
                      >We can combine more directional classes to achieve our
                      goal.</span
                    >
                  </td>
                </tr>
                <tr>
                  <td class="nowrap">
                    <span class="c-important">.m-0--sm</span><br />
                    <span class="c-important">.mt-32--md</span><br />
                    <span class="c-important">.pb-16--lg</span><br />
                    <span class="c-important">.pb-0--xl</span>
                  </td>
                  <td>
                    <span class="fwb">Responsive spacing utility classes</span>,
                    every class, we descibed above have it's responsive version.
                    <span class="c-important">--sm</span> will be used only on
                    small screens<br />
                    <span class="c-important">--md</span> on medium screens<br />
                    <span class="c-important">--lg</span> on large screens<br />
                    <span class="c-important">--xl</span> on extralarge
                    screens<br />
                  </td>
                </tr>
              </tbody>
            </table>

            <h5 class="mb-xs">Let's have an example</h5>
            <code-block
              lang="html"
              :code="SPACINGS_BASIC_EXAMPLE"
              class="mb-lg"
            />

            <p>
              Let's focus on the first content div (<span class="fsi"
                >Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span
              >), we used utility classes which will set elements
              <span class="ff-mono">paddings</span>,&nbsp;
              <span class="ff-mono">width</span>,&nbsp;
              <span class="ff-mono">background-color</span>,&nbsp;
              <span class="ff-mono">color</span>(text). What might be harder to
              understand is when will be
              <span class="ff-mono">margin-right</span> and
              <span class="ff-mono">margin-bottom</span> applied on the first
              div. Div will have
              <span class="ff-mono nowrap">margin-right:&nbsp;0;</span> only on
              <span class="fwb">small screen</span>, when divs will be one under
              each other, in that same scenario will be added
              <span class="ff-mono">margin-bottom: 2rem</span>
              to add space between divs. In all other scenarios (divs are next
              to each other) will be applied
              <span class="ff-mono">margin-right: 2rem;</span>.
            </p>

            <h5 class="mb-xs">
              Result of our example (resize screen to see how the elements
              change)
            </h5>
            <component-example
              component-name="Utility Classes"
              class="c-component-example--no-gaps mt-0"
            >
              <div v-html="SPACINGS_BASIC_EXAMPLE"></div>
            </component-example>
          </div>
        </section>
      </div>
      <aside class="o-page__side o-page__side--last"></aside>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { getArticleNavSections } from "@/helpers/htmlHelpers";

import CodeBlock from "@/components/common/CodeBlock.vue";
import ComponentExample from "@/components/common/ComponentExample.vue";

import { SPACINGS_BASIC_EXAMPLE } from "@/code_examples/utilities/html/Examples";
import { GENERATED_SPACING_CLASSES_EXAMPLE } from "@/code_examples/utilities/css/Examples";

export default defineComponent({
  name: "SpacingsUtilityClasses",
  components: {
    CodeBlock,
    ComponentExample,
  },
  setup() {
    const sections = getArticleNavSections();
    return {
      sections,
      SPACINGS_BASIC_EXAMPLE,
      GENERATED_SPACING_CLASSES_EXAMPLE,
    };
  },
});
</script>
