image: node:16.18.0-slim

stages:
  - build
  - deploy

default:
  interruptible: true

build:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/**/*
    expire_in: 1 week
  only:
    - master

deploy:
  stage: deploy
  image:
    name: registry.enrian.dev/shared/infra-dockers/deploy:latest
  script:
    - eval $(ssh-agent)
    - cat ${DEPLOY_PRIVATE_KEY} | ssh-add -
    - rsync -e "ssh -F ./ssh-config" -rv ./dist/ ${CI_COMMIT_BRANCH}:/var/www/design.enrian.dev/
  interruptible: false
  only:
    - master
